name: .NET Core

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: [linux]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Build
      run: make build
    - name: Test
      run: make test
