name: Publish apps

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Build
      run: make build

    - name: Publish
      run: make publish

    # Upload linux artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: linux-x64
        path: dist/linux-x64

    # Upload macOS artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: osx-x64
        path: dist/osx-x64

    # Upload windows artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: win-x64
        path: dist/win-x64
