name: publish
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenChart
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Build
        run: ./tasks.sh build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: .

  publish-linux:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout OpenChart
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: Publish
        run: ./tasks.sh publish

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux-x64
          path: dist/linux-x64

  publish-osx:
    if: github.event.pull_request.draft == false
    runs-on: macos-latest
    needs: build

    steps:
      - name: Checkout OpenChart
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: Publish
        run: ./tasks.sh publish

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: osx-x64
          path: dist/osx-x64

  publish-win:
    if: github.event.pull_request.draft == false
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout OpenChart
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: Publish
        run: ./tasks.sh publish
        shell: bash

      - name: Bundle
        run: ./tasks.sh bundle
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: win-x64
          path: bundle/Output/install-OpenChart.exe
