name: run-tests
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenChart
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install SDL
        run: sudo apt install -y libsdl2-dev libsdl2-image-dev

      - name: Restore dependencies
        run: ./tasks.sh restore

      - name: Run tests
        run: ./tasks.sh test
